CREATE TABLE foods_raw (
    product_name        VARCHAR2(500),
    brands              VARCHAR2(300),
    categories          VARCHAR2(500),
    ingredients         CLOB,
    nutriscore_grade    VARCHAR2(5),
    nova_group          NUMBER,
    ecoscore_grade      VARCHAR2(5),
    allergens           VARCHAR2(500),
    energy_kcal         NUMBER,
    fat_100g            NUMBER,
    saturated_fat_100g  NUMBER,
    carbs_100g          NUMBER,
    sugars_100g         NUMBER,
    fiber_100g          NUMBER,
    proteins_100g       NUMBER,
    salt_100g           NUMBER,
    sodium_100g         NUMBER,
    contains_gluten     NUMBER(1),
    contains_dairy      NUMBER(1),
    contains_nuts       NUMBER(1),
    contains_soy        NUMBER(1),
    contains_eggs       NUMBER(1),
    contains_fish       NUMBER(1),
    food_type           VARCHAR2(200)
);
